package com.salesupload.createcolumn.enitity;
// Generated Feb 27, 2019 2:26:34 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Columntypemaster generated by hbm2java
 */
@Entity
@Table(name = "columntypemaster", catalog = "dalmia")
public class Columntypemaster implements java.io.Serializable {

	private short columntypeid;
	private String name;
	private Integer active;

	public Columntypemaster() {
	}

	public Columntypemaster(short columntypeid) {
		this.columntypeid = columntypeid;
	}

	public Columntypemaster(short columntypeid, String name, Integer active) {
		this.columntypeid = columntypeid;
		this.name = name;
		this.active = active;
	}

	@Id

	@Column(name = "columntypeid", unique = true, nullable = false, precision = 4, scale = 0)
	public short getColumntypeid() {
		return this.columntypeid;
	}

	public void setColumntypeid(short columntypeid) {
		this.columntypeid = columntypeid;
	}

	@Column(name = "name", length = 32)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "active")
	public Integer getActive() {
		return this.active;
	}

	public void setActive(Integer active) {
		this.active = active;
	}

}
