package com.salesupload.Tabledef.enitity;
// Generated Feb 23, 2019 4:13:39 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tabledefinition generated by hbm2java
 */
@Entity
@Table(name = "tabledefinition", catalog = "dalmia")
public class Tabledefinition  {

	private int tabledefinitionid;
	private Short filetypeid;
	private String filetypename;
	private String tablename;
	private String excelfile;
	

	private String tablecreated;
	private Integer active;

	public Tabledefinition() {
	}

	public Tabledefinition(int tabledefinitionid) {
		this.tabledefinitionid = tabledefinitionid;
	}

	public Tabledefinition(int tabledefinitionid, Short filetyeid, String filetyename, String tablename,
			String excelfile, String tablecreated, Integer active) {
		this.tabledefinitionid = tabledefinitionid;
		this.filetypeid = filetypeid;
		this.filetypename = filetypename;
		this.tablename = tablename;
		this.excelfile = excelfile;
		this.tablecreated = tablecreated;
		this.active = active;
	}

	@Id

	@Column(name = "tabledefinitionid", unique = true, nullable = false, precision = 8, scale = 0)
	public int getTabledefinitionid() {
		return this.tabledefinitionid;
	}

	public void setTabledefinitionid(int tabledefinitionid) {
		this.tabledefinitionid = tabledefinitionid;
	}

	@Column(name = "filetypeid", precision = 4, scale = 0)
	public Short getFiletypeid() {
		return this.filetypeid;
	}

	public void setFiletypeid(Short filetypeid) {
		this.filetypeid = filetypeid;
	}

	@Column(name = "filetypename", length = 16)
	public String getFiletypename() {
		return this.filetypename;
	}

	public void setFiletypename(String filetypename) {
		this.filetypename = filetypename;
	}

	@Column(name = "tablename", length = 32)
	public String getTablename() {
		return this.tablename;
	}

	public void setTablename(String tablename) {
		this.tablename = tablename;
	}

	@Column(name = "excelfile", length = 128)
	public String getExcelfile() {
		return excelfile;
	}

	public void setExcelfile(String excelfile) {
		this.excelfile = excelfile;
	}

	@Column(name = "tablecreated", length = 4)
	public String getTablecreated() {
		return this.tablecreated;
	}

	public void setTablecreated(String tablecreated) {
		this.tablecreated = tablecreated;
	}

	@Column(name = "active")
	public Integer getActive() {
		return this.active;
	}

	public void setActive(Integer active) {
		this.active = active;
	}

}
