package com.salesupload.tablecreationdetail.entity;
// Generated Feb 27, 2019 2:29:44 PM by Hibernate Tools 5.2.11.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tablecreationdetail generated by hbm2java
 */
@Entity
@Table(name = "tablecreationdetail", catalog = "dalmia")
public class Tablecreationdetail implements java.io.Serializable {

	private int creationid;
	private int tabledefinitionid;
	private String columnname;
	private String columndescription;
	private Short columntypeid;
	private String columntypevalue;
	private String defaultvalue;
	private Integer ismandotary;
	private Integer ispk;
	private Integer active;
	private Integer createdby;
	private Integer modifiedby;
	private Date modifiedon;
	private Date createdon;
	private String macaddress;
	private String ipaddress;

	public Tablecreationdetail() {
	}

	public Tablecreationdetail(int creationid, int tabledefinitionid) {
		this.creationid = creationid;
		this.tabledefinitionid = tabledefinitionid;
	}

	public Tablecreationdetail(int creationid, int tabledefinitionid, String columnname, String columndescription,
			Short columntypeid, String columntypevalue, String defaultvalue, Integer ismandotary, Integer ispk,
			Integer active, Integer createdby, Integer modifiedby, Date modifiedon, Date createdon, String macaddress,
			String ipaddress) {
		this.creationid = creationid;
		this.tabledefinitionid = tabledefinitionid; 
		this.columnname = columnname;
		this.columndescription = columndescription;
		this.columntypeid = columntypeid;
		this.columntypevalue = columntypevalue;
		this.defaultvalue = defaultvalue;
		this.ismandotary = ismandotary;
		this.ispk = ispk;
		this.active = active;
		this.createdby = createdby;
		this.modifiedby = modifiedby;
		this.modifiedon = modifiedon;
		this.createdon = createdon;
		this.macaddress = macaddress;
		this.ipaddress = ipaddress;
	}

	@Id

	@Column(name = "creationid", unique = true, nullable = false, precision = 8, scale = 0)
	public int getCreationid() {
		return this.creationid;
	}

	public void setCreationid(int creationid) {
		this.creationid = creationid;
	}

	@Column(name = "tabledefinitionid", nullable = false, precision = 8, scale = 0)
	public int getTabledefinitionid() {
		return this.tabledefinitionid;
	}

	public void setTabledefinitionid(int tabledefinitionid) {
		this.tabledefinitionid = tabledefinitionid;
	}

	@Column(name = "columnname", length = 32)
	public String getColumnname() {
		return this.columnname;
	}

	public void setColumnname(String columnname) {
		this.columnname = columnname;
	}

	@Column(name = "columndescription", length = 128)
	public String getColumndescription() {
		return this.columndescription;
	}

	public void setColumndescription(String columndescription) {
		this.columndescription = columndescription;
	}

	@Column(name = "columntypeid", precision = 4, scale = 0)
	public Short getColumntypeid() {
		return this.columntypeid;
	}

	public void setColumntypeid(Short columntypeid) {
		this.columntypeid = columntypeid;
	}

	@Column(name = "columntypevalue", length = 16)
	public String getColumntypevalue() {
		return this.columntypevalue;
	}

	public void setColumntypevalue(String columntypevalue) {
		this.columntypevalue = columntypevalue;
	}

	@Column(name = "defaultvalue", length = 32)
	public String getDefaultvalue() {
		return this.defaultvalue;
	}

	public void setDefaultvalue(String defaultvalue) {
		this.defaultvalue = defaultvalue;
	}

	@Column(name = "ismandotary")
	public Integer getIsmandotary() {
		return this.ismandotary;
	}

	public void setIsmandotary(Integer ismandotary) {
		this.ismandotary = ismandotary;
	}

	@Column(name = "ispk")
	public Integer getIspk() {
		return this.ispk;
	}

	public void setIspk(Integer ispk) {
		this.ispk = ispk;
	}

	@Column(name = "active")
	public Integer getActive() {
		return this.active;
	}

	public void setActive(Integer active) {
		this.active = active;
	}

	@Column(name = "createdby", precision = 8, scale = 0)
	public Integer getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(Integer createdby) {
		this.createdby = createdby;
	}

	@Column(name = "modifiedby", precision = 8, scale = 0)
	public Integer getModifiedby() {
		return this.modifiedby;
	}

	public void setModifiedby(Integer modifiedby) {
		this.modifiedby = modifiedby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modifiedon", length = 26)
	public Date getModifiedon() {
		return this.modifiedon;
	}

	public void setModifiedon(Date modifiedon) {
		this.modifiedon = modifiedon;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdon", length = 26)
	public Date getCreatedon() {
		return this.createdon;
	}

	public void setCreatedon(Date createdon) {
		this.createdon = createdon;
	}

	@Column(name = "macaddress", length = 32)
	public String getMacaddress() {
		return this.macaddress;
	}

	public void setMacaddress(String macaddress) {
		this.macaddress = macaddress;
	}

	@Column(name = "ipaddress", length = 32)
	public String getIpaddress() {
		return this.ipaddress;
	}

	public void setIpaddress(String ipaddress) {
		this.ipaddress = ipaddress;
	}

}
